# DNA Fiber Assay Analysis of ORC1 mutants - short version

In [1]:
import pandas as pd

# Parameters

In [10]:
INPUT_IOD = "/mnt/c/users/helen/Dropbox/CIMA_PHD/DATA/MICROSCOPY/DNA_FIBERS/MGS/4rd_experiment_GOOD/data_analysis_graphs/results/iod_kb.xlsx"
INPUT_SPEED = "/mnt/c/users/helen/Dropbox/CIMA_PHD/DATA/MICROSCOPY/DNA_FIBERS/MGS/4rd_experiment_GOOD/data_analysis_graphs/results/replication_speed.xlsx"

IOD_STATS = "/mnt/c/users/helen/Dropbox/CIMA_PHD/DATA/MICROSCOPY/DNA_FIBERS/MGS/4rd_experiment_GOOD/data_analysis_graphs/results/stats_u_iod.xlsx"
SPEED_STATS = "/mnt/c/users/helen/Dropbox/CIMA_PHD/DATA/MICROSCOPY/DNA_FIBERS/MGS/4rd_experiment_GOOD/data_analysis_graphs/results/stats_u_replication_speed.xlsx"

# Data Import

In [11]:
iod = pd.read_excel(INPUT_IOD)
speed = pd.read_excel(INPUT_SPEED)

iod_stats = pd.read_excel(IOD_STATS)
speed_stats = pd.read_excel(SPEED_STATS)

In [12]:
iod_stats

     Comparison  WT_n  Sample_n     U   p-value
0   WT vs siSCR    50        55  1439  0.683698
1  WT vs siORC1    50        25   306  0.000344
2    WT vs MGS1    50        28   434  0.005683
3    WT vs MGS2    50        48   945  0.070505
4    WT vs MGS3    50        48   711  0.000517
5    WT vs MGS4    50        23   377  0.019013
6    WT vs MGS5    50        30   544  0.041124

In [13]:
speed_stats

     Comparison  WT_n  Sample_n     U   p-value
0   WT vs siSCR    74        59  2364  0.413658
1  WT vs siORC1    74        56  1638  0.041536
2    WT vs MGS1    74        38   918  0.002737
3    WT vs MGS2    74        60  1801  0.061134
4    WT vs MGS3    74        64  1607  0.001166
5    WT vs MGS4    74        53  1187  0.000156
6    WT vs MGS5    74        47  1321  0.026402

# Graphs with statistics

In [14]:
from plotting import boxplot_with_statistics

### IOD graph

### Speed graph